### ISSUE TITLE
Create documentation for an environment setup

### ISSUE THREAD

**Issue by Dosbodoke** [International-Slackline-Association/slackmap-ui#6]
I forked the repository and run `yarn install` & `yarn start` but got an error

![image](https://user-images.githubusercontent.com/78118656/217875811-eaf56269-25b3-4321-9f45-b107c08cb87e.png)

The `.env.dev` file is ignored by `.gitignore` and it has no clue about how the configuration should be.

The backend also isn't clear on how to setup it up.

**Comment by Can-Sahin** [comment]
As it says in env.example you should fill in the values. Naturally I don't wanna broadcast the URLs for the bots scanning the got repositories. If you wanna run locally send an email to slackmap@slacklineinternational.org
